apiVersion: v2
name: domain-alfresco-chart
description: A Helm chart for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "1.16.0"

dependencies:
- name: alfresco-common
  version: 2.1.0
  repository: https://alfresco.github.io/alfresco-helm-charts/
- name: postgresql
  version: 12.8.5
  repository: oci://registry-1.docker.io/bitnamicharts
  condition: postgresql.enabled
- name: common
  alias: alfresco-digital-workspace
  repository: https://activiti.github.io/activiti-cloud-helm-charts
  version: 7.11.0
  condition: >-
    alfresco-digital-workspace.enabled
- name: activemq
  version: 3.3.0
  repository: https://alfresco.github.io/alfresco-helm-charts/
  condition: activemq.enabled
- name: alfresco-transform-service
  version: 0.2.0
  repository: https://alfresco.github.io/alfresco-helm-charts/
  condition: alfresco-transform-service.enabled
- name: alfresco-search-service
  alias: alfresco-search
  repository: https://alfresco.github.io/alfresco-helm-charts/
  version: 1.3.0
  condition: alfresco-search.enabled
- name: alfresco-share
  alias: share
  version: 0.1.0
  repository: https://alfresco.github.io/alfresco-helm-charts/
  condition: share.enabled
